import type { Metadata } from "next";
import "./globals.css";
import NavBar from './Components/NavBar'
import { Poppins } from 'next/font/google'
import { ThemeProvider } from "../components/ui/theme-provider"
import Footer from "./Components/Footer";


export const metadata: Metadata = {
  title: "Astro Steam - Level up cost simulator",
  description: "Generated by Misty",
  icons: {
    icon: '/icon.png',
  },
};
export const pop = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight:['100','200','400','500','600','700','800']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={pop.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
      <NavBar/>
      <main className='relative overflow-hidden'>{children}</main>
      <Footer/>
      </ThemeProvider>
      </body>
    </html>
  );
}
